# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0002_remove_acta_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='organizador',
        ),
    ]
