# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0003_remove_acta_organizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoitems',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
